// src/App.tsx
import React, { useCallback, useState, useEffect } from 'react'
import { Routes, Route, NavLink } from 'react-router-dom'
import Particles from 'react-tsparticles'
import { loadSlim } from 'tsparticles-slim'
import type { Engine } from 'tsparticles-engine'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSun, faMoon, faEnvelope, faPhoneSquare } from '@fortawesome/free-solid-svg-icons'
import { faLinkedin, faXingSquare, faGithub } from '@fortawesome/free-brands-svg-icons'
import Home from './pages/Home'
import About from './pages/About'
import Work from './pages/Work'
import { particlesConfig } from './particlesConfig'

const EMAIL = 'mdbelal.aiub@gmail.com'
const MOBILE = '+4915734402228'

export default function App() {
  const [dark, setDark] = useState(true)
  const [menuOpen, setMenuOpen] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem('theme')
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches
    const isDark = stored === 'dark' || (!stored && prefersDark)
    setDark(isDark)
    document.documentElement.classList.toggle('dark', isDark)
  }, [])

  const toggleTheme = () => {
    const next = !dark
    setDark(next)
    document.documentElement.classList.toggle('dark', next)
    localStorage.setItem('theme', next ? 'dark' : 'light')
  }

  const particlesInit = useCallback(async (engine: Engine) => {
    await loadSlim(engine)
  }, [])

  const navLinkClass = ({ isActive }: { isActive: boolean }) =>
    `px-4 py-2 text-sm font-medium rounded-lg transition-all duration-200 ${
      isActive
        ? 'text-white bg-indigo-500/20 border border-indigo-500/40'
        : 'text-slate-400 hover:text-white hover:bg-white/5'
    }`

  return (
    <div className="relative min-h-screen overflow-x-hidden">
      {/* Particles background */}
      <Particles
        id="tsparticles"
        init={particlesInit}
        options={particlesConfig}
        className="fixed inset-0 -z-10"
      />

      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 px-6 py-4">
        <div className="max-w-6xl mx-auto flex items-center justify-between glass rounded-2xl px-6 py-3">
          {/* Logo */}
          <NavLink to="/" className="text-white font-bold text-lg tracking-tight">
            <span className="gradient-text">BH</span>
            <span className="text-slate-300 ml-1 text-sm font-normal">/ dev</span>
          </NavLink>

          {/* Desktop nav links */}
          <div className="hidden md:flex items-center gap-1">
            <NavLink to="/" end className={navLinkClass}>Home</NavLink>
            <NavLink to="/about" className={navLinkClass}>About</NavLink>
            <NavLink to="/work" className={navLinkClass}>Work</NavLink>
            <a
              href="/assets/Md Belal Hosen_CV.pdf"
              target="_blank"
              rel="noreferrer"
              className="ml-2 px-4 py-2 text-sm font-semibold rounded-lg border border-indigo-500 text-indigo-400 hover:bg-indigo-500 hover:text-white transition-all duration-200"
            >
              Resume ↗
            </a>
          </div>

          {/* Theme toggle + mobile menu button */}
          <div className="flex items-center gap-3">
            <button
              onClick={toggleTheme}
              className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10 transition-all duration-200"
              aria-label="Toggle theme"
            >
              <FontAwesomeIcon icon={dark ? faSun : faMoon} />
            </button>
            <button
              className="md:hidden p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/10"
              onClick={() => setMenuOpen(!menuOpen)}
              aria-label="Menu"
            >
              <div className="w-5 h-0.5 bg-current mb-1" />
              <div className="w-5 h-0.5 bg-current mb-1" />
              <div className="w-5 h-0.5 bg-current" />
            </button>
          </div>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="md:hidden mt-2 glass rounded-2xl px-6 py-4 flex flex-col gap-2">
            <NavLink to="/" end className={navLinkClass} onClick={() => setMenuOpen(false)}>Home</NavLink>
            <NavLink to="/about" className={navLinkClass} onClick={() => setMenuOpen(false)}>About</NavLink>
            <NavLink to="/work" className={navLinkClass} onClick={() => setMenuOpen(false)}>Work</NavLink>
            <a
              href="/assets/Md Belal Hosen_CV.pdf"
              target="_blank"
              rel="noreferrer"
              className="px-4 py-2 text-sm font-semibold rounded-lg border border-indigo-500 text-indigo-400 text-center"
              onClick={() => setMenuOpen(false)}
            >
              Resume ↗
            </a>
          </div>
        )}
      </nav>

      {/* Left social panel (desktop) */}
      <div className="fixed left-5 bottom-0 z-40 hidden lg:flex flex-col items-center gap-4 pb-0">
        <a href="https://www.linkedin.com/in/md-belal-hosen/" target="_blank" rel="noreferrer"
           className="text-slate-500 hover:text-indigo-400 transition-colors duration-200 hover:-translate-y-1 transform">
          <FontAwesomeIcon icon={faLinkedin} size="lg" />
        </a>
        <a href="https://www.xing.com/profile/MdBelal_Hosen/cv" target="_blank" rel="noreferrer"
           className="text-slate-500 hover:text-cyan-400 transition-colors duration-200 hover:-translate-y-1 transform">
          <FontAwesomeIcon icon={faXingSquare} size="lg" />
        </a>
        <a href="https://github.com/imbelal" target="_blank" rel="noreferrer"
           className="text-slate-500 hover:text-white transition-colors duration-200 hover:-translate-y-1 transform">
          <FontAwesomeIcon icon={faGithub} size="lg" />
        </a>
        <a href={`mailto:${EMAIL}`}
           className="text-slate-500 hover:text-indigo-400 transition-colors duration-200 hover:-translate-y-1 transform">
          <FontAwesomeIcon icon={faEnvelope} size="lg" />
        </a>
        <a href={`tel:${MOBILE}`}
           className="text-slate-500 hover:text-cyan-400 transition-colors duration-200 hover:-translate-y-1 transform">
          <FontAwesomeIcon icon={faPhoneSquare} size="lg" />
        </a>
        <div className="w-px h-20 bg-gradient-to-b from-indigo-500/50 to-transparent mt-2" />
      </div>

      {/* Right email panel (desktop) */}
      <div className="fixed right-5 bottom-0 z-40 hidden lg:flex flex-col items-center gap-4">
        <a
          href={`mailto:${EMAIL}`}
          className="text-slate-500 hover:text-indigo-400 transition-colors duration-200 text-xs tracking-widest font-medium"
          style={{ writingMode: 'vertical-rl' }}
        >
          {EMAIL}
        </a>
        <div className="w-px h-20 bg-gradient-to-b from-indigo-500/50 to-transparent" />
      </div>

      {/* Page content */}
      <main className="relative z-10 pt-24 pb-20 px-4 lg:px-16 xl:px-24">
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/about" element={<About />} />
          <Route path="/work" element={<Work />} />
        </Routes>
      </main>
    </div>
  )
}

// src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { ParticlesConfig } from 'src/app/particles-config';
import { faMoon } from '@fortawesome/free-solid-svg-icons';
import { faSun } from '@fortawesome/free-solid-svg-icons';
import { faLinkedin } from '@fortawesome/free-brands-svg-icons';
import { faXingSquare } from '@fortawesome/free-brands-svg-icons';
import { faGithub } from '@fortawesome/free-brands-svg-icons';
import { faEnvelope } from '@fortawesome/free-solid-svg-icons';
import { faPhoneSquare } from '@fortawesome/free-solid-svg-icons';
import { environment } from 'src/environments/environment';


declare var particlesJS: any;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})

export class AppComponent implements OnInit {

  title = 'imbelal_portfulio';
  faMoon = faMoon;
  faSun = faSun;
  faLinkedin = faLinkedin;
  faXing = faXingSquare;
  faGithub = faGithub;
  faMail = faEnvelope;
  faMobile = faPhoneSquare;
  email = environment.email;
  mobile = environment.mobile;
  mobileNo = `tel:${environment.mobile}`;


  public ngOnInit(): void {
    this.invokeParticles();
    this.changeThemeColor();
  }

  public invokeParticles(): void {
    particlesJS('particles-js', ParticlesConfig, function () { });
  }

  toggleTheme() {
    // Whenever the user explicitly chooses theme color
    if (localStorage.getItem('theme') === 'dark')
      localStorage.setItem('theme', ''); // replacing dark string with empty string
    else
      localStorage.setItem('theme', 'dark');

    this.changeThemeColor();
  }

  changeThemeColor() {
    // On page load or when changing themes, best to add inline in `head` to avoid FOUC
    if (localStorage.getItem('theme') === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }

}

<!-- particles background -->
<div id="particles-js" class="absolute top-0 left-0 right-0 z-1"></div>

<!-- menus -->

<div class="container z-999 w-auto absolute top-5 right-10">
    <a href="" routerLink="" class="z-50 px-5 py-2 dark:text-white hover:font-bold">Home</a>
    <a href="" routerLink="about" class="z-50 px-5 py-2 dark:text-white hover:font-bold">About</a>
    <a href="" routerLink="work" class="z-50 px-5 py-2 dark:text-white hover:font-bold">Work</a>
    <a href="assets/Md Belal Hosen_CV.pdf"
        class="z-50 px-5 py-2 dark:text-white hover:font-bold ring ring-yellow rounded animate-pulse"
        target="_blank">Resume</a>
</div>

<!-- center body -->
<div class="container z-10 mx-auto">
    <router-outlet></router-outlet>
</div>

<!-- right panel -->
<div class="z-10 ">
    <fa-icon [icon]="faSun"
        class="text-2xl invisible dark:visible dark:text-white absolute top-4 right-2 cursor-pointer animate-pulse"
        (click)="toggleTheme()"></fa-icon>
    <fa-icon [icon]="faMoon" class="text-2xl dark:hidden absolute top-4 right-2 cursor-pointer animate-pulse"
        (click)="toggleTheme()"></fa-icon>
    <div class=" absolute right-2 top-20">
        <a href="https://www.linkedin.com/in/md-belal-hosen/" target="_blank">
            <fa-icon [icon]="faLinkedin"
                class="text-2xl text-blue cursor-pointer animate-pulse transition duration-700 ease-in-out"></fa-icon>
        </a> <br>
        <a href="https://www.xing.com/profile/MdBelal_Hosen/cv" target="_blank">
            <fa-icon [icon]="faXing"
                class="text-2xl text-green cursor-pointer animate-pulse transition duration-700 ease-in-out"></fa-icon>
        </a> <br>
        <a href="https://github.com/imbelal" target="_blank">
            <fa-icon [icon]="faGithub"
                class="text-2xl text-orange cursor-pointer animate-pulse transition duration-700 ease-in-out"></fa-icon>
        </a>
        <br>
        <a href="mailto:{{email}}" title="{{email}}">
            <fa-icon [icon]="faMail"
                class="text-2xl text-yellow cursor-pointer animate-pulse transition duration-700 ease-in-out"></fa-icon>
        </a>
        <br>
        <a [attr.href]="mobileNo | byPassSecurity" title="{{mobile}}">
            <fa-icon [icon]="faMobile"
                class="text-2xl text-purple cursor-pointer animate-pulse transition duration-700 ease-in-out"></fa-icon>
        </a>
    </div>
</div>

<!-- right side email panel -->
<div class="absolute top-2/3 right-[-70px]  rotate-90 z-50 md:visible invisible">
    <a href="mailto:{{email}}" title="{{email}}" class="dark:text-white">
        {{email}}
    </a>
</div>
